---
proxy-providers:
  gamemaster:
    type: file
    path: "gamemaster.yaml"
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 99
  sosmedmaster:
    type: file
    path: "sosmedmaster.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
  streammaster:
    type: file
    path: "streammaster.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
  browsermaster:
    type: file
    path: "browsermaster.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
proxy-groups:
- name: mei-cft-master
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - gamemaster
  - sosmedmaster
  - streammaster
  - browsermaster
  url: http://www.gstatic.com/generate_204
  interval: '99'
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 127.0.0.1:1053
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - "*.ntp.org.cn"
  - "*.openwrt.pool.ntp.org"
  - time1.cloud.tencent.com
  - time.ustc.edu.cn
  - pool.ntp.org
  - ntp.ubuntu.com
  - ntp.aliyun.com
  - ntp1.aliyun.com
  - ntp2.aliyun.com
  - ntp3.aliyun.com
  - ntp4.aliyun.com
  - ntp5.aliyun.com
  - ntp6.aliyun.com
  - ntp7.aliyun.com
  - time1.aliyun.com
  - time2.aliyun.com
  - time3.aliyun.com
  - time4.aliyun.com
  - time5.aliyun.com
  - time6.aliyun.com
  - time7.aliyun.com
  - "*.time.edu.cn"
  - time1.apple.com
  - time2.apple.com
  - time3.apple.com
  - time4.apple.com
  - time5.apple.com
  - time6.apple.com
  - time7.apple.com
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - localhost.ptlogin2.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - "+.xboxlive.com"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "+.battlenet.com.cn"
  - "*.googleapis.com"
  - googleapis.com
  - "*.tendawifi.com"
  - tendawifi.com
  - "*.tplinkwifi.com"
  - tplinkwifi.com
  - "*.telegram.com"
  - telegram.com
  - "*.mozila.com"
  - mozila.com
  - "*.ucbrowser.com"
  - ucbrowser.com
  - "*.operamini.com"
  - operamini.com
  - "*.yandex.com"
  - yandex.com
  - "*.yahoo.com"
  - yahoo.com
  - "*.google.com"
  - google.com
  - "*.whatsapp.net"
  - "*.whatsapp.com"
  - whatsapp.net
  - whatsapp.com
  - "*.instagram.com"
  - instagram.com
  - "*.facebook.com"
  - facebook.com
  - "*.youtube.com"
  - youtube.com
  - ytimg.com
  - "*.ytimg.com"
  - "*.tiktok.com"
  - tiktok.com
  - "*.resso.app"
  - "*.spotify.com"
  - spotify.com
  - 3.asia.pool.ntp.org
  - 2.asia.pool.ntp.org
  - 1.asia.pool.ntp.org
  - 0.asia.pool.ntp.org
  - 3.id.pool.ntp.org
  - 2.id.pool.ntp.org
  - 1.id.pool.ntp.org
  - 0.id.pool.ntp.org
  fallback-filter:
    geoip: false
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
ipv6: false
profile:
  store-selected: true
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- MATCH,mei-cft-master
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
